Update rm_from_etc_hosts

diff --git a/scripts/rm_from_etc_hosts b/scripts/rm_from_etc_hosts
--- a/scripts/rm_from_etc_hosts
+++ b/scripts/rm_from_etc_hosts
@@ -9,7 +9,7 @@ function gREP() {
 }
 
 if [[ $(id -u) -ne "0" ]]; then
-    printf "[error] You must run this as root... try sudo?" >&2
+    printf "[error] You must run this as root... try sudo?\n\n" >&2
     exit 1
 fi
 
